### ISSUE TITLE
User docker instance for the tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/pyocclient#112]
Instead of bootstrapping ownCloud in Travis with the PHP env, use the Python environment + OC in docker.

**Comment by SergioBertolinSG** [comment]
I don't get exactly what are you suggesting here.

Run a docker server inside travis or point to containers in our servers?

**Comment by PVince81** [comment]
@SergioBertolinSG I was rather thinking about having Travis fire up its own docker, if that's even possible

**Comment by PVince81** [comment]
done
