### ISSUE TITLE
reduce accepted codes to code "100"

### ISSUE THREAD

**Issue by individual-it** [owncloud/pyocclient#113]
The User Provisioning API returns different codes. 100,101,102 etc.
pyocclient often regards the OC code 102 as OK.
**create_group()**: https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L1072
but 102 here means "group already exists"
**create_user()**: https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L768
but 102 here means: "username already exists"
**add_user_to_group()**: https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L877
but 102 here means: "group does not exist", so the user was definitely not added to that group

etc.
I think we should raise an exception for every return code that is not "100"

Here the details of codes: https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html?highlight=provision#users-addtogroup

**Comment by PVince81** [comment]
Argh, you're right. The weird OCS codes.

**Comment by individual-it** [comment]
__check_ocs_status() raises an ResponseError also if a not accepted OC code is returned.
could we have 2 different exceptions?
one for real HTTP errors, like 404, 403 etc.
and one for OC error messages that are not "100"

Then a client application can decide itself what to do and how to react on the exceptions

**Comment by PVince81** [comment]
Maybe a OCSResponseError for the weird OCS codes ?

**Comment by individual-it** [comment]
what about that pull request #114 ?

**Comment by PVince81** [comment]
Resolved with https://github.com/owncloud/pyocclient/pull/114

**Comment by individual-it** [comment]
It's not finished because I still have to delete all the occurrence of "102" in owncloud.py

**Comment by individual-it** [comment]
done a new pull request #116 
sorry deleted accidentally my old private branch
