### ISSUE TITLE
login() returns "None" after successful AND after not successful login

### ISSUE THREAD

**Issue by individual-it** [owncloud/pyocclient#118]
when running login "None" is returned in both cases. Nothing is different between a successful and an unsuccessful login.
Only after the next API call you know if the login did succeed or not. There you get a 404 HTTP Error if the login did not succeed.
Would be great to know directly after login() what happened.

Is this a problem in pyocclient or in the core?

**Comment by PVince81** [comment]
pyocclient should throw an exception if the login failed, see https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L229

Did you find a situation where it doesn't throw anything ?

**Comment by PVince81** [comment]
Oh wait... we're opening the "index.php"... of course we might get the login page instead.

Hmmm, we might need to find a better endpoint for logging in then.

**Comment by PVince81** [comment]
The core "bug" is that there is no proper endpoint for authentication, that is already known.

We need to find a workaround for pyocclient.
Unfortunately using the OCS endpoints also doesn't work properly, see https://github.com/owncloud/pyocclient/pull/53#issuecomment-63872289

**Comment by PVince81** [comment]
Maybe authenticating against the webdav endpoint could work: "remote.php/webdav". That's probably what the desktop and mobile clients do.

**Comment by individual-it** [comment]
should not already

    self.__session.auth = (user_id, password)
return an error?

**Comment by PVince81** [comment]
No. This row only adds the auth information to the future request (and any request done within that session).
The actual request is done here with `get()`: https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L221

**Comment by individual-it** [comment]
for me (with 8.1) both URL remote.php/webdav and ocs/v1.php/cloud/capabilities return only one cookie 
so the bug https://github.com/owncloud/core/issues/12930  seems to be fixed

But then the cookie that was returned by remote.php/webdav or  ocs/v1.php/cloud/capabilities does not get accepted for the WebDAV communication, the cookie of index.php of course works fine

**Comment by individual-it** [comment]
It works when we behave like the desktop client and get the cookie from status.php and send the login details with every request. https://github.com/owncloud/pyocclient/pull/121#issuecomment-136123243

We also have to make 2 calls for every login.
1. get the session from status.php
2. check if the login works. In my pull request I've done it by checking the capabilities URL

**Comment by individual-it** [comment]
Any reason that fix would not work?

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/pyocclient/pull/121
