### ISSUE TITLE
It's not possible to download files with '#' in their names

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/pyocclient#123]
The file is uploaded fine in 8.0.5 but a 404 error is thrown trying to download the file. The file can be downloaded fine from the server 8.1.3 (checked with the web interface and webdav by using curl).
Other weird chars can be affected.

**Comment by PVince81** [comment]
PR here with test first: https://github.com/owncloud/pyocclient/pull/124

**Comment by PVince81** [comment]
Indeed, the test confirms it. It seems to be only for download.

**Comment by PVince81** [comment]
Fixed https://github.com/owncloud/pyocclient/pull/124
