### ISSUE TITLE
create_user as non-admin

### ISSUE THREAD

**Issue by ConnyOnny** [owncloud/pyocclient#129]
When you make an account a "group admin", it can create users in the group (via web interface), but with pyocclient I get `owncloud.owncloud.HTTPResponseError: HTTP error: 401` with this response body: `<?xml version="1.0"?>
<ocs><meta><status>failure</status><statuscode>997</statuscode>  <message>Unauthorised</message></meta><data/></ocs>`

My best guess is this: As non-admin but group admin you can only create users in your group, but the create_user method doesn't provide a way to specify a group for the user to be in initially. So ownCloud says "no, you can't create a user who is not in your group". Again, this is only a guess.

I guess this is relevant for the 0.2 release: #115

**Comment by PVince81** [comment]
This requires support from the server: https://github.com/owncloud/core/issues/18382

**Comment by PVince81** [comment]
@ConnyOnny can you retry with OC 9.0 pre-alpha (from git) ? The call should work now.
