### ISSUE TITLE
signature of search_users

### ISSUE THREAD

**Issue by cosenal** [owncloud/pyocclient#130]
I am not clear about what is returned by search_users.

Say you have the following snippet:
```
oc = owncloud.Client(...)
oc.login('test', 'test')
e = oc.search_users('test')
print list(e.itertext())
```
The following is printed:
```
['\n   ', 'test', '\n   ', 'testcore', '\n  ']
``` 
Is this intentional or is it a bug? What's the return value of search_users supposed to be? The docstring generically says "a list of users"

**Comment by PVince81** [comment]
@individual-it can you clarify ? If I remember well you added this function recently.
Thanks.

**Comment by cosenal** [comment]
cc'ing also @jnfrmarks, because git-blame suggests to do so :)

**Comment by individual-it** [comment]
the XML is fine, also the extracting of the items looks fine for me, but itertext output seems sometimes to be strange.

Can somebody make sense of that:

````
>>> import xml.etree.ElementTree as ET
>>> xml="""<?xml version="1.0"?> 
... <ocs>
...  <meta>
...   <status>ok</status>
...   <statuscode>100</statuscode>
...   <message/>
...  </meta>
...  <data>
...   <users>
...    <element>2EC62722-4AED-4566-B642-EFE4A9C90E88</element>
...    <element>test1</element>
...    <element>test2</element>
...   </users>
...  </data>
... </ocs>
... """
>>> tree = ET.fromstring(xml)
>>> users = tree.find('data/users')
>>> print list(users.itertext())
['\n   ', '2EC62722-4AED-4566-B642-EFE4A9C90E88', '\n   ', 'test1', '\n   ', 'test2', '\n  ']
>>> for user in users.itertext(): print(user)
... 

   
2EC62722-4AED-4566-B642-EFE4A9C90E88

   
test1

   
test2

````

But:
````
>>> print ("".join(users.itertext()))

   2EC62722-4AED-4566-B642-EFE4A9C90E88
   test1
   test2
  
>>> for user in users: print(user)
... 
<Element 'element' at 0x7f3fb18b4d10>
<Element 'element' at 0x7f3fb18b4d50>
<Element 'element' at 0x7f3fb18b4d90>
>>> for user in users: print(user.text)
... 
2EC62722-4AED-4566-B642-EFE4A9C90E88
test1
test2
>>> 

Here a similar problem:
http://stackoverflow.com/questions/19370711/element-tree-python-itertext-not-working-with-line-breaks

**Comment by cosenal** [comment]
There is nothing too strange going on here, except that `tree.find` returns also the newlines as subelements of the users.element.

The loop over users works fine and `itertext()` doesn't, just because itertext loops over "the element and all subelements", as reported in the python docs.
Also, the joined string from your example does include the newlines, otherwise you'd see a single-line string in the output.

I will make a PR, as soon as I figure out what's the actual value we want this function to return.

**Comment by cosenal** [comment]
@PVince81 
Freenode netsplitting, so I'll ask here.
I am not clear about the API itself: https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_provisioning_api.html#users-getusers
What's returned there, just a list of usernames? Then we could return the same here: for the example above the list of strings ['test1', 'test2']

**Comment by PVince81** [comment]
Yes, it's just a list of users names (array of strings)

**Comment by cosenal** [comment]
alright, PR coming
