### ISSUE TITLE
import owncloud module fails for example

### ISSUE THREAD

**Issue by vfulco** [owncloud/pyocclient#135]
Can't find this with  pip or on github?  Any trailheads would be appreciated.  Using Ubuntu 15.04 with both python and p3k. TIA.

**Comment by cosenal** [comment]
What do you mean? Did the installation with pip go through? If by p3k, you mean Python3, notice that's not supported yet.

**Comment by vfulco** [comment]
Strange, re-installed and --upgraded thru pip and now it works.  Any tips on how to get SSL terminated to work?  Thank you.
