### ISSUE TITLE
Add config.py to gitignore, prepare example and make travis work.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/pyocclient#141]
Configuration file should be ignored by git, everybody can have their own config.py file.

- [x] Add config.py to .gitignore .
- [x] Create config.py.sample which makes clear fields which can be used.
- [x] Travis execution should be happy with this change.

**Comment by PVince81** [comment]
- [ ] update README to tell people to rename it

**Comment by SergioBertolinSG** [comment]
Pr here https://github.com/owncloud/pyocclient/pull/142
