### ISSUE TITLE
publicUpload not working on ES

### ISSUE THREAD

**Issue by jorgeboucas** [owncloud/pyocclient#150]
Enabling publicUpload is not working on ES probably due to the 'Files Drop' function implemented from 8.0.3 ES on.

Of notice, folders that are part of 'Files Drop' are also not listed as shares.

**Comment by PVince81** [comment]
@jorgeboucas in what way is this related to pyocclient ? pyocclient cannot upload files to public links, there is no function for that.

If you meant to raise this as a core issue, please raise in https://github.com/owncloud/core

Also note that 8.0.3 is old and outdated and you might want to update to at least 8.0.10.

**Comment by jorgeboucas** [comment]
@PVince81 just got some feedback that publicUpload is disabled by the admin on the instant I am using - 8.2.

I will raise the need for 'Files Drop' management over PUT on the core.

Thanks!
