### ISSUE TITLE
HTTP error: 405 when putting file contents

### ISSUE THREAD

**Issue by ErikPel** [owncloud/pyocclient#157]
Not sure if this is problem with my owncloud server installation or the python client.
Made a quick example how I can reproduce my error

```
import os
import owncloud
import time

class errorExample:
    def __init__(self):
        self.file_name = 'test.txt'
        self.content = 'Hello world!'
        self.subdir = 'subdir'
        self.temp_dir = tempfile.gettempdir() + '/pyocclient_test%s/' % int(time.time())
        os.mkdir(self.temp_dir)

        self.client = owncloud.Client('http://erikpellikka.com/owncloud', single_session = True)
        self.client.login('testuser', 'ayylmao')
        self.test_root = 'testfolder%s' % int(time.time())
        if not self.test_root[-1] == '/':
            self.test_root += '/'
        if not self.test_root[0] == '/':
            self.test_root = '/' + self.test_root
        self.client.mkdir(self.test_root)

    def test_mkdir(self):
        """Test subdirectory creation"""
        self.client.mkdir(self.test_root + self.subdir)
        self.client.file_info(self.test_root + self.subdir)

    def test_put_file_contents(self):
        """Test creating remote file with given contents"""
        self.client.mkdir(self.test_root + self.subdir)
        self.client.put_file_contents(self.test_root + self.subdir + '/' + self.file_name, self.content)

exampleclass = errorExample()
exampleclass.test_mkdir()
exampleclass.test_put_file_contents()
```

this gives me 

```
  File "example.py", line 37, in <module>
    test.test_put_file_contents()
  File "example.py", line 32, in test_put_file_contents
    self.client.mkdir(self.test_root + self.subdir)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 622, in mkdir
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 1657, in __make_dav_request
owncloud.owncloud.HTTPResponseError: HTTP error: 405

```

The file doesn't get made at all but the directory is. Am I misunderstanding something on how to use python client or is there something else wrong?

**Comment by PVince81** [comment]
Your code looks correct. Maybe check in your access_log whether the call itself is correct, maybe the URL wasn't built properly or is missing a slash ?

**Comment by ErikPel** [comment]
@PVince81 it works when I take the mkdir out of the second function since it's creating the same folder.
Shouldn't the mkdir return true even if the folder already exist instead of throwing
` 405 The resource you tried to create already exists
`
 error?

**Comment by PVince81** [comment]
Depends on what we want the API to do.
In Webdav terms, creating a folder that already exists is not allowed and returns 405.
So ideally, pyocclient should also reflect that somehow.

Another idea would be to add a kwargs option "ignore_existing=True" that makes it return true even if 405 came back.

**Comment by ErikPel** [comment]
Alright. How do the tests work? Those two functions are in the tests but the assert true for the second one still returns true?

**Comment by PVince81** [comment]
> How do the tests work?

From what I remember we never try to recreate an existing folder in the unit tests.

**Comment by ErikPel** [comment]
@PVince81 
I must be missing something really obvious then. Maybe I should just take a break and come back with fresh eyes.
https://github.com/owncloud/pyocclient/blob/master/owncloud/test/test.py#L137
https://github.com/owncloud/pyocclient/blob/master/owncloud/test/test.py#L209
Doesn't this already get made earlier?

**Comment by PVince81** [comment]
No, the setup code doesn't create the "subdir" sub dir. It only creates the test root.

**Comment by PVince81** [comment]
@ErikPel still happening ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
