### ISSUE TITLE
always getting owncloud.ResponseError: HTTP error: 401 when creating a directory

### ISSUE THREAD

**Issue by cedjo** [owncloud/pyocclient#159]
connection and logging work fine.
when doing oc.mkdir("testdir") I always received:

```
>>> import owncloud
>>> oc=owncloud.Client("https://demo.owncloud.org/")
>>> oc.login("test","test")
>>> oc.mkdir("testdir")
```

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/owncloud/__init__.py", line 430, in mkdir
    return self.__make_dav_request('MKCOL', path)
  File "/usr/local/lib/python2.7/site-packages/owncloud/__init__.py", line 620, in __make_dav_request
    raise ResponseError(res)
owncloud.ResponseError: HTTP error: 401**

using owncloud demo server https://demo.owncloud.org or any other test server.

**Comment by PVince81** [comment]
It looks like for some reason the session is not kept or the cookies are not working.
No idea why. Do you have the latest Python's "requests" library installed ?

**Comment by cedjo** [comment]
requests (2.9.1) installed

**Comment by PVince81** [comment]
The code you posted works for me locally, against the demo instance.
- python-2.7.10-4.1.x86_64
- requests (2.9.1)

Did you try with pyocclient from git master ? (not 0.1)

**Comment by cedjo** [comment]
git master version solved the issue... Thanks
