### ISSUE TITLE
pyocclient not sending basic auth headers

### ISSUE THREAD

**Issue by lz1irq** [owncloud/pyocclient#160]
### Setup
Debian 8 (Jessie) stable with python 2.7.9. I have `pyocclient 0.1` installed in a virtualenv via pip.
OwnCloud is running on a CentOS7 machine under Apache. External requests and SSL are handled via a nginx reverse proxy, but I am using the local address (`192.168.122.121:2100`) to avoid any possible issues associated with nginx.

### Issue
The code I am running is:
```
import owncloud
user = 'username'
password = 'password'

ocl = owncloud.Client('http://192.168.122.121:2100')
ocl.login(username, password)
ocl.list('/')
```

When I do this, I get a `401 Not Authorized` error. From the OC admin panel logs:
```
Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't 
send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception
\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth
\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\
/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105):
 call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV
\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html
\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248):
 Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP
\\Response))\n#4 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV
\\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\
/o...')\n#6 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth
\/Plugin.php","Line":188,"User":"ivo"} 
```

### Debugging

I decided to listen in via wireshark. First, I ran the following request via curl:

`curl -D - -X PROPFIND -k http://$username:$password@192.168.122.121:2100/remote.php/carddav`

Which resulted in this packet being sent:
![basic auth package](https://i.imgur.com/GEl6Mby.png)
and a `HTTP/1.1 200 OK` response.

However, when I run the code above, it generates this package:
![pyocclient](https://i.imgur.com/t7RhNOX.png)
which leads to a `HTTP/1.1 401 Unauthorized` response.

Desktop clients and web login work fine. I may be missing something really obvious, but I've bothered to write out a detailed report just in case.

**Comment by PVince81** [comment]
Can you try with the master version of pyocclient ? (upcoming 0.2)
0.1 is quite old

**Comment by lz1irq** [comment]
@PVince81 Thank you very much for the amazingly fast response. It works just fine with the current master version. I wasn't sure whether the master branch is always in a working state, so I didn't try that.

**Comment by PVince81** [comment]
Yeah... I hope to find time to do the 0.2 release one of these days...
