### ISSUE TITLE
HTTP error: 401 after owncloud upgrade to 9.0.2

### ISSUE THREAD

**Issue by dmcevoy** [owncloud/pyocclient#161]
I've been using the owncloud package for about a month now. This is great and thanks for creating this package. I have a fairly simple job the automatically takes daily updated files from a local server and uploads them to my owncloud server. Today, my owncloud desktop client was not working and I was prompted to upgrade to version 9.0.2. I did this and the desktop client works again. However, my file transfer job now fails with a HTTP error: 401. This is all being run on a UNIX server.

I've tried a simple test that also fails:

```
import owncloud

oc = owncloud.Client('https://my/server')

oc.login('user', 'password')
oc.mkdir('testdir')
```

This results in:

```
ResponseError                             Traceback (most recent call last)
<ipython-input-5-271a2b6ab42e> in <module>()
----> 1 oc.mkdir('testdir')

/home/model/software/anaconda2/lib/python2.7/site-packages/owncloud/__init__.pyc in mkdir(self, path)
    428         if not path[-1] == '/':
    429             path = path + '/'
--> 430         return self.__make_dav_request('MKCOL', path)
    431
    432     def delete(self, path):

/home/model/software/anaconda2/lib/python2.7/site-packages/owncloud/__init__.pyc in __make_dav_request(self, method, path, **kwargs)
    618         if res.status_code == 204 or res.status_code == 201:
    619             return True
--> 620         raise ResponseError(res)
    621
    622     def __parse_dav_response(self, res):

ResponseError: HTTP error: 401
```

When I run `oc.put_file` I get the same error. I get know error using my login with `oc.login`.

Thanks in advance.

**Comment by PVince81** [comment]
@dmcevoy I just ran the test suite against v9.0.2 (from git) and it runs fine, no login issues.

Are you using pyocclient 0.1 or the master version ? Best is to use the master version for now until 0.2 is released.

**Comment by PVince81** [comment]
If not, please check the server's owncloud.log for more clues.

**Comment by PVince81** [comment]
> my owncloud desktop client was not working

Looks like something broke on your server even before the upgrade.
It is very unlikely to be a pyocclient bug.

Please investigate your server logs. If you think there's a bug, report to https://github.com/owncloud/core/issues (you can ping me there too). Thanks.

**Comment by dmcevoy** [comment]
I've attached a recent owncloud error log. The owncloud-error.log-21050503
seems closely related to my problem. This was provided to me by the server
administrator, which is not me. I'm not sure what to make of the error
messages. Is there any chance you could point me in the right direction
based on these error messages?

If it is any help the server administrator said he recently patched up to
owncloud 8.1. Is this something that should be reported on the owncloud
issues board?

Thanks!

**Comment by dmcevoy** [comment]
@PVince81 How can I install the master version as you suggest? I did have v0.1 installed.

Thanks.

**Comment by dmcevoy** [comment]
@PVince81 Sorry to keep bugging you (no pun intended), but just for some closure I switched to the master version and now it works fine.
