### ISSUE TITLE
PB with Get_shares

### ISSUE THREAD

**Issue by ceeeeb** [owncloud/pyocclient#164]
Hello, 

I use this code for test

``` python
import owncloud
oc = owncloud.Client('https://owncloud.comp.tld')
oc.login('login', password')

if oc.is_shared('testdir') == False:
        print "No share"
        link_info = oc.share_file_with_link('testdir')
        id_link=link_info.get_link()
        print id_link
else:
        print "share Exist"
        id_info=oc.get_shares('testdir')
        id_link=oc.get_share(id_info[0].get_id())
        print id_link.get_link()
```

When Share does not exist, it's Ok , i get id link
`
No share
https://owncloud.comp.tld/index.php/s/SEGaJTjnBxH2Ko3
`
But when share exist, there is no id link (None)
`share Exist
None
`

Can you Help me

**Comment by PVince81** [comment]
@ceeeeb are you using pyocclient 0.2 or master ? Don't use 0.1 as it's old and broken

**Comment by ceeeeb** [comment]
No , I use pyocclient 0.2

**Comment by ceeeeb** [comment]
I installed the master version, but I still have the same problem

Do you have a idea ?

**Comment by PVince81** [comment]
Not yet, haven't had time to try and reproduce this.
Which exact ownCloud server version are you connecting to ?

**Comment by PVince81** [comment]
@SergioBertolinSG @rullzer might know as this is about the OCS Share API ?

**Comment by ceeeeb** [comment]
ownCloud 8.1.8 (stable)

**Comment by ceeeeb** [comment]
https://owncloud.xxx.xx/ocs/v1.php/config

<ocs>
<meta>
<status>ok</status>
<statuscode>100</statuscode>
<message/>
</meta>
<data>
<version>1.7</version>
<website>ownCloud</website>
<host>owncloud.xxx.xx</host>
<contact/>
<ssl>false</ssl>
</data>
</ocs>

**Comment by ceeeeb** [comment]
Sorry

`
<ocs>
<meta>
<status>ok</status>
<statuscode>100</statuscode>
<message/>
</meta>
<data>
<version>1.7</version>
<website>ownCloud</website>
<host>owncloud.xxx.xx</host>
<contact/>
<ssl>false</ssl>
</data>
</ocs>
`

**Comment by ceeeeb** [comment]
I did a test with the debugger , I do not see the link attribute (May be share_with ?)
`
ipdb> l
     11         print id_link
     12 else:
     13         print "share Exist"
     14         id_info=oc.get_shares('testdir')
     15         import ipdb; ipdb.set_trace()
---> 16         id_link=oc.get_share(id_info[0].get_id())
     17         print id_link.get_link()
     18
     19

ipdb> id_info[0]
ShareInfo(share_with_displayname=None,file_target=/Shared/testdir,displayname_owner=selfiebox,share_type=3,permissions=1,token=0yO4tVoxJN675qD,expiration=None,share_with=None,storage_id=home::selfiebox,path=/testdir,file_parent=6269,uid_owner=selfiebox,id=100,stime=1464115189)
ipdb> n
> /home/pi/selfieBox/selfiebox/tt.py(17)<module>()
     16         id_link=oc.get_share(id_info[0].get_id())
---> 17         print id_link.get_link()
     18

ipdb> id_link
ShareInfo(share_with_displayname=None,file_target=/Shared/testdir,displayname_owner=selfiebox,share_type=3,permissions=1,token=0yO4tVoxJN675qD,expiration=None,share_with=None,storage_id=home::selfiebox,path=/testdir,file_parent=6269,uid_owner=selfiebox,id=100,stime=1464115189)
ipdb>

`

**Comment by SergioBertolinSG** [comment]
Please have in mind this behaves differently before 8.2 and after 8.2. In this PR I differentiated between both tests https://github.com/owncloud/pyocclient/pull/143 @PVince81 btw it needs review ✨

**Comment by ceeeeb** [comment]
FYI , 
i upgraded my owncloud server in 8.2.5 now i see the link in ShareInfo but the name of attribut is url and not link ?
`
share_info {'share_with_displayname': None, 'file_target': '/Shared/testdir', 'displayname_owner': 'selfiebox', 'share_type': '3', 'permissions': '1', 'url': 'https://owncloud.xxx.xx/index.php/s/0yO4tVoxJN675qD', 'token': '0yO4tVoxJN675qD', 'expiration': None, 'share_with': None, 'storage_id': 'home::selfiebox', 'path': '/testdir', 'file_parent': '6269', 'uid_owner': 'selfiebox', 'id': '100', 'stime': '1464115189'}

`

**Comment by SergioBertolinSG** [comment]
@ceeeeb yes you are right, I'll prepare a PR to fix that.

**Comment by SergioBertolinSG** [comment]
Ok, inside that dict the name is link and not url. But not sure if smashbox depends on that name, I'll need to check that before merging it https://github.com/owncloud/pyocclient/pull/165 .

**Comment by rullzer** [comment]
I think the link item is just missing in 8.1

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/pyocclient/pull/165 ?

**Comment by PVince81** [comment]
closing due to lack of feedback
