### ISSUE TITLE
login vs set credentials

### ISSUE THREAD

**Issue by poggenpower** [owncloud/pyocclient#166]
Hello,

the login function is a little bit misleading, because the REST API for OC is stateless, see [Link](https://doc.owncloud.org/server/8.0/developer_manual/core/externalapi.html).
In most cases it has no effect if login was successful or not. 
API requests don't care about session cookies. You need to send user and passwd instead.
e.g. the sample code from the readme will not work with the login function. You need to place user and passwd in the URL.

It would be great to have a function "setCredentials" to avoid ugly URLs like https://user:password@domain.tld/owncloud/

Bye 
 Thomas

**Comment by PVince81** [comment]
This is not 100% correct. When using the OC APIs and a session cookie is available, it will reuse that session. The same applies for the Webdav API. This is how the desktop client works for example.

It is indeed possible to reauthenticate for every call but using sessions will save some overhead.

I guess that documentation will need to be adjusted at some point...

**Comment by poggenpower** [comment]
I found the issue.

used "https://domain.tld/onwcloud" as URL, like the sample code do.
login() try to authenticate using this URL, but I will get back a "http redirect", which means: http 200 OK, but following content:
```
<head>
        <script type="text/javascript"> window.location.href="index.php"; </script>
        <meta http-equiv="refresh" content="0; URL=index.php">
</head>
</html>
```
The request module in not automatically follow this redirect.
If I user "://domain.tld/onwcloud/index.html" it works fine. 
May be if you have a approriate .htaccess with some rewrites, this bug will not occur.

**Comment by PVince81** [comment]
Looks like a setup issue. Are you using the correct .htaccess bundled with ownCloud ?

**Comment by poggenpower** [comment]
I run two owncloud/netxcloud server version9.0.x since years without issues. I don't think that the rewrite is a core requirement. It simply makes the URLs a little bit nicer.

**Comment by PVince81** [comment]
Can you check the admin page whether you have warnings ?

I was mostly referring to this part https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html?highlight=htaccess#apache-web-server-configuration that is needed for the htaccess file to work in the first place.

**Comment by poggenpower** [comment]
I have a warning about strict "Strict-Transport-Security" and missing Mem-Cache. Nothing that should impact this behaviour. 
The .htacces in the oc-root is the one OC creates while installation. Nothing changed. 
Checked this file. Didn't found something regarding index.php.

**Comment by PVince81** [comment]
Hmmm, then maybe it's in the web server or PHP configuration that something is missing.
On my openSUSE box when I install Apache2 + PHP there are already some rules about the redirect.

Anyway, like you said maybe we can change the login URL to be a different one, like "index.php" or so to make it work on more configurations.

**Comment by poggenpower** [comment]
I found a index.html with the redirect code I have posted above in the OC-root. 
This is distributed with OC per default. My Server is Ubuntu, Apache2 + PHP. Index.html has priority for index.php. If I remove the index.html, the code works fine. 
But If you can add index.php per default, this would be great. 
Thanks

**Comment by PVince81** [comment]
Yeah, thinking of it, it's probably better to target the correct URL directly instead of relying on a redirect, which technically creates an additional request.

**Comment by PVince81** [comment]
@poggenpower are you using pyocclient 0.2 ? I see that the code uses the capabilities endpoint to do the login (actually the login can be done on any API).

**Comment by poggenpower** [comment]
I have installed with pip and didn't check the version before. 
It is 0.1 not 0.2.
Are you planing to distribute 0.2 to the standard pip repositories?

**Comment by PVince81** [comment]
It's already there:
```
  % pip search pyocclient
pyocclient (0.2)  - Python client library for ownCloud
```

**Comment by poggenpower** [comment]
Ahh fund it, but 0.2 is in egg format, which is not supported by pip, but easy_install.
Isn't it better to distribute in a pip compatible format? as you did for 0.1?
pip works much better with virtualenv.
See: https://packaging.python.org/en/latest/wheel_egg/

**Comment by PVince81** [comment]
Hmm strange, I didn't know these are different things. Tbh I'm new with these pip/egg stuff.

I think I used the command `python setup.py bdist_egg upload -s -r https://pypi.python.org/pypi` (from my shell history) to publish it.

Do I need to republish it using a different command ?

**Comment by PVince81** [comment]
Ok, I managed to publish it as before with "sdist": https://pypi.python.org/pypi/pyocclient/0.2

Please try upgrading now.

**Comment by poggenpower** [comment]
Thanks, now it works fine. Thanks for all your work. Great job.

**Comment by PVince81** [comment]
Thanks, glad to hear it works now for you!
