### ISSUE TITLE
Rounding of chunk_count in __put_file_chunked can be off by 1

### ISSUE THREAD

**Issue by dpickem** [owncloud/pyocclient#175]
In the function[ __put_file_chunked](https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L586) instead of 

chunk_count = size / chunk_size

the line should read

chunk_count = math.ceil(size / chunk_size)

Otherwise the subsequent cast to int(chunk_count) on line 594 may discard the last chunk of a file.

**Comment by PVince81** [comment]
Hmmm, mind submitting a PR to fix it ?
I see you might be new to Github so it's ok if you don't.

Let me know.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/pyocclient/pull/177

**Comment by PVince81** [comment]
apparently this issue cannot happen because of this code: https://github.com/owncloud/pyocclient/pull/177#issuecomment-255334458

but anyway, I guess that when reading the code it is easy to miss, so I'll change it to use the `math.ceil` approach
