### ISSUE TITLE
How to patch __make_ocs_request to provide additional parameters?

### ISSUE THREAD

**Issue by bobatsar** [owncloud/pyocclient#179]
I would like to pass additional parameters to the requests module (like a timeout) to all calls.

I thought I would just subclass the `Client` and overwrite the `__make_ocs_request` Function.

Unfortunately the `__make_ocs_request` starts with double underscores (as the `__session` attribute) and thus prohibits proper inheritance.

What is the reason that so many functions and members are implemented with double underscores?

Is there another way to pass default parameters to the requests module?

**Comment by PVince81** [comment]
Hmm, the purpose of double underscores here were only to make these methods private.

If you think they should be protected (is there such a thing in python?) feel free to do so in a PR.
Alternatively you can also make a PR that adds a way to provide custom arguments to `__make_ocs_request` and potentially any other calls.

However if all you need is a global timeout value, I suggest you rather add a new constructor arg `timeout` or a generic constructor arg `request_options` which would contain options that every call would use when calling the "requests" library.

What do you think ?

**Comment by bobatsar** [comment]
There is no real private or protected in python (see http://radek.io/2011/07/21/private-protected-and-public-in-python/)

But if members are only marked with a single underscore, at least subclasses are allowed to access the members (protected convention).

I would also need to add some additional headers and the timeout so for me the subclassing would be the best.

If you don't mind, I will do a PR to change some of the members to "protected".

**Comment by PVince81** [comment]
> If you don't mind, I will do a PR to change some of the members to "protected".

Sounds good!

**Comment by bobatsar** [comment]
See PR #180 

Additionally I did some code cleanup (mostly pycharm suggestions). I hope this was ok.

**Comment by bobatsar** [comment]
#180 merged
