### ISSUE TITLE
pip install pyocclient fails

### ISSUE THREAD

**Issue by artemistomaras** [owncloud/pyocclient#181]
I am unable to install pyocclient via pip.

`pip install pyocclient` gives me:

Collecting pyocclient
  Using cached pyocclient-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SYNELI~1\AppData\Local\Temp\pip-build-zma856gv\pyocclient\s
etup.py", line 18, in <module>
        + '\n')
    OSError: [Errno 22] Invalid argument: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SYNELI~1
\AppData\Local\Temp\pip-build-zma856gv\pyocclient\

**Comment by PVince81** [comment]
Hmm, I wonder if it's related to the symlinks for the docs since Windows doesn't support symlinks

**Comment by artemistomaras** [comment]
I managed to get it to work by manual installing:
`git clone https://github.com/owncloud/pyocclient.git`
`cd pyocclient`
`python setup.py install`

I tested `pip install pyocclient` on both Windows 7 x64 and Ubuntu 16.04.
Only on Windows I got the mentioned error

**Comment by bobatsar** [comment]
I also tried it on a windows 10 machine and it seems to be working. I can't untar the archive manually but pip's internal tar mechanism seems to work fine. (pip 9.0.1)

**Comment by PVince81** [comment]
I have no idea what I could do here to make this better. If someone can give me pointers if there is something that can be done in packaging (setuptools) to make this work, please let me know.

**Comment by PVince81** [comment]
is this still an issue ?

**Comment by artemistomaras** [comment]
@PVince81 I cannot reproduce it since I have since migrated to Linux land for development. You may as well close this issue ...

**Comment by PVince81** [comment]
thanks for the feedback.
