### ISSUE TITLE
get files and directories ID in listing

### ISSUE THREAD

**Issue by lwolf** [owncloud/pyocclient#188]
Hi, I'm trying to use API to save current state of the folder and I need to have unique ID.
But, it looks like `list` API call does not return id.
Is there any workaround to get it? 
How difficult could it be to add?

**Comment by PVince81** [comment]
Try adding the "oc:id" property to the existing PROPFIND.

Best would be to extend https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L384 and also `file_info` to allow passing a list of arbitrary namespaces XML properties to insert into the PROPFIND. Then have a way on the FileInfo object to retrieve them.

Once this is in the API, your client would just need to call `list(dir, 1, ['{http://owncloud.org/ns}id'])` to request the listing including that property

**Comment by lwolf** [comment]
Hi, thanks for the quick reply.

I never used webdav before, so, could you please clarify the logic here?
How can I add this `oc:id` to the request. 
Should it be part of the header?

**Comment by PVince81** [comment]
I suggest you read on a bit about Webdav PROPFIND.

Or open the file list of ownCloud in the web browser and look at the network console for the PROPFIND. You'll see how a request looks like and a response.

Basically the PROPFIND body can say what properties you want to read and they will appear in the response.

**Comment by lwolf** [comment]
Thanks, I got it to work

**Comment by PVince81** [comment]
Did you make any changes to pyocclient ? If yes, would be great if you could send these as a PR 😄

**Comment by lwolf** [comment]
I was thinking about making PR at the beginning.
But I ended up with hardcoded version of the request body with `oc:id` field in it.
Which is more like a workaround/hack then a solution worth a PR.

https://github.com/lwolf/pyocclient/commit/44c885be684b7fcfa803f91e42d7af6f647fd07f

**Comment by PVince81** [comment]
I see. I suggest to only include "oc:id" and not the other properties if you don't use them. They will slow down the request needlessly.

**Comment by lwolf** [comment]
thanks, I removed other fields. I thought that it will override everything and return only that specific field.

**Comment by tstreibl** [comment]
Hi, I would need help in this point too, having to admit that my skills are unsufficient to write a proper "propfind" request in oder to get the additional parameters in the "oc" and "nc" tags.

 In my case I need the "oc:owner-display-name" information to identify who created a new folder in a shared folder and to send an email to this user. 

Would be so great when the file_info call/class would be enhanded by these properties like PVince81 suggested. At least an example of how to modify "_make_dav_request" or the hack from "Iwolf" would be a starting point for me.

**Comment by tstreibl** [comment]
Hi, just realized that Iwolf already gave a link on his solution. I was able tofix my problem with this hack, too. Thanks a lot to Iwolf. Two small comments (I'm unexperienced so handle with care):

Please add tag <oc:owner-id/>. This allows to get all user information with a subsequent get_user(user) call.

Fixing the list call doesn't fix the file_info call/class jet. In my eyes the file_info call is just a special case of the list call. The "list" call at the moment is confusing because it returns an empty list when used on a single file or directory (with depth=0 or depth=1). Reason for this is that list always eliminates the first element in the return value in order to list only files and not the directories (in this case ther is only one element!). This is confusing because user might want to get information about a directory as well (see #195). Suggestion: modify list to return res for [depth=0} and for any other depth return res[1:].  Then file_info would be just a call to self.list(path, depth=0) [0]

**Comment by PVince81** [comment]
In general, the PROPFIND for both `list()` and `file_info()` need to be extended to support requesting custom attributes. This would then make it possible for any caller to supply whatever attributes they'd like to see in the response.

**Comment by tstreibl** [comment]
yes, that would be a great enhancement

**Comment by skwee** [comment]
Just a hack but does the job. As _make_dav_request passes all it's arguments to the generic requests call, you can just add a payload using the data-parameter.
A full list of available protperties can be found here:
[https://docs.nextcloud.com/server/12/developer_manual/client_apis/WebDAV/index.html](https://docs.nextcloud.com/server/12/developer_manual/client_apis/WebDAV/index.html)
Found the solution by following PVince81 advice to look at the Browser-Console and the network-traffic of the nextcloud webgui.

```
    def file_info(self, path):
        """Returns the file info for the given remote file

        :param path: path to the remote file
        :returns: file info
        :rtype: :class:`FileInfo` object or `None` if file
            was not found
        :raises: HTTPResponseError in case an HTTP error status was returned
        """
        res = self._make_dav_request('PROPFIND', path, headers={'Depth': '0'}, data="""
<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:prop>
    <oc:fileid />
    <oc:owner-display-name />
    <oc:owner-id />
  </d:prop>
</d:propfind>""")
        if res:
            return res[0]
        return None
```

**Comment by PVince81** [comment]
thanks to https://github.com/owncloud/pyocclient/pull/248 you can now pass in extra attribues to query, so query the "oc:fileid"
