### ISSUE TITLE
Compatibility with Nextcloud 

### ISSUE THREAD

**Issue by bittner** [owncloud/pyocclient#189]
Is the Python client compatible with Nextcloud? (currently version 11)

If not, do you plan to create _a)_ a compatibility layer, or _b)_ fork of the project for Nextcloud?

References
-----------
I don't know which API docs are actually relevant of the ones I found. Here they are: (alphabetical order)

- [Client API’s docs](https://docs.nextcloud.com/server/12/developer_manual/client_apis/index.html)
- [External API docs](https://docs.nextcloud.com/server/12/developer_manual/core/externalapi.html)
- [RESTful API docs](https://docs.nextcloud.com/server/12/developer_manual/app/api.html)
- [User Provisioning API docs](https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_provisioning_api.html)

**Comment by PVince81** [comment]
I personally have no plans regarding Nextcloud.

As this is open-source, people can either send pull requests to make it compatible (if needed) or fork it.

**Comment by bittner** [comment]
**Full disclosure:** You guys are competitors. And there's obviously some grief from the split-up.

I'm sorry about that. But, yes, it's open source. You're right.
