### ISSUE TITLE
I get Http error: 500 uploading a file

### ISSUE THREAD

**Issue by jacastaneda** [owncloud/pyocclient#190]
When i try to upload a file via web dav i get this:  

Exception: {"Message":"An exception occurred while executing 'UPDATE \"oc_filecache\" SET \"mtime\" = GREATEST(\"mtime\", ?), \"etag\" = ? WHERE (\"storage\" = ?) AND (\"path_hash\" IN ('d41d8cd98f00b204e9800998ecf8427e', '45b963397aa40d4a0063e0d85e4fe7a1', '62e67db19ff62ebb206a52077799e9b5'))' with params [\"1490067978.03\", \"58d0a6843bb78\", 1]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: \"1490067978.03\"","Exception":"Doctrine\\DBAL\\Exception\\DriverException","Code":0,"Trace":"#0 \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE \"oc_file...', Array)\n#2 \/var\/www\/html\/lib\/private\/DB\/Connection.php(209): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE \"oc_file...', Array, Array)\n#3 \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)\n#4 \/var\/www\/html\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php(141): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 \/var\/www\/html\/lib\/private\/Files\/Cache\/Propagator.php(87): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 \/var\/www\/html\/lib\/private\/Files\/Cache\/HomePropagator.php(48): OC\\Files\\Cache\\Propagator->propagateChange('files\/zlivioDat...', '1490067978.03', 0)\n#7 \/var\/www\/html

May someonw help me please

**Comment by PVince81** [comment]
Which version of pyocclient are you using ?

It looks like its sending a float timestamp "1490067978.03" which also makes the server bug apparently...

**Comment by jacastaneda** [comment]
I am using 0.4 version @PVince81

**Comment by PVince81** [comment]
Ok, so this means that properly the "stat" result has float timestamps. These must be changed to be trimmed here:
- https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L514
- https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L588

What python version are you using and what filesystem is the file you're trying to upload on ?
Just curious because I never saw this error before.

**Comment by jacastaneda** [comment]
Thank you very much @PVince81 you are very kind.

I am using python 2.7.6 and i just tried to upload a simple txt file, here is the test code:

oc = owncloud.Client('http://x.x.x.x:8080)
oc.login('user, 'pass')
oc.put_file('data/prueba.jpg', '/home/jcastaneda/test.txt')
link_info = oc.share_file_with_link('datat/text.txt')
print "Here is your link: " + link_info.get_link()

What i have done is to change the "mtime" column (oc_filecache table) type of my owncloud database (which is in postgres) from integer to number and the issue is gone, but it dont atack the root cause of it.

Best regards and thank you again.

**Comment by PVince81** [comment]
Related: https://github.com/owncloud/pyocclient/issues/176
