### ISSUE TITLE
Shared_id if possible.

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#194]
Hello Sir, I have a simple question.
Could you please give a small example related to: how could I obtain: param share_id: Share ID (int)
share_id of the shared folder?  

for example userA shared a folder with me and I want to accept it. How could I learn the shared folder's shared_id? Basically pending share items to be accepted:
<img width="148" alt="screen shot 2017-04-18 at 14 12 22" src="https://cloud.githubusercontent.com/assets/18537398/25132220/760f09cc-2451-11e7-9ede-60d6891ec3f3.png">

`def accept_remote_share(self, share_id):`

**Comment by PVince81** [comment]
AFAIK you'd need to call `list_open_remote_share()` first
