### ISSUE TITLE
share_file_with_user error

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#199]
`oc.share_file_with_user( "/home/prc/oc/path", "ee14ea28-b869-1036-8080-9dbd8c6b1579@b2drop.eudat.eu");`

Gives me following error:

```
  File "test.py", line 19, in <module>
    oc.share_file_with_user( "/home/prc/oc/path", "ee14ea28-b869-1036-8080-9dbd8c6b1579@b2drop.eudat.eu");
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1246, in share_file_with_user
    self._check_ocs_status(tree)
  File "/usr/local/lib/python2.
```

I have around 200 files to share. By GUI it is takes very long time to share each one by hand :(

[Q] How could I fix this error? Thank you for your valuable time and help.

**Comment by PVince81** [comment]
Is there more to the error ? I don't see any actual exception name in the trace you posted above.

It would also useful to check owncloud.log to see if there is an error there matching this one in case it's an OC bug.

**Comment by avatar-lavventura** [comment]
Thank you sir. How could I obtain owncloud.log? 

/home/prc/oc/path it the path I wanted share which locates under my mounted folder and "ee14ea28-b869-1036-8080-9dbd8c6b1579@b2drop.eudat.eu" is the public id I would like to share. Is it the correct way I am using it? @PVince81

**Comment by avatar-lavventura** [comment]
I would be appreciated if you could help me related to this issue. I couldn't find any owncloud.log @PVince81 

mkdir oc
sudo mount.davfs https://b2drop.eudat.eu/remote.php/webdav/ oc

python.py: With the same user name which I mounted I logged in and share a folder located under my mounted folder.
oc = owncloud.Client('https://b2drop.eudat.eu/')
oc.login('aalimog1@binghamton.edu', password );

oc.share_file_with_user( "/home/alper/oc/a", "ee14ea28-b869-1036-8080-9dbd8c6b1579@b2drop.eudat.eu")

**Error:**
```
Traceback (most recent call last):
  File "alper.py", line 16, in <module>
    oc.share_file_with_user( "/home/alper/oc/a", "3d8e2dc2-b855-1036-807f-9dbd8c6b1579@b2drop.eudat.eu")
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1246, in share_file_with_user
    self._check_ocs_status(tree)
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1602, in _check_ocs_status
    raise OCSResponseError(r)
owncloud.owncloud.OCSResponseError: OCS error: 404
```

**Comment by PVince81** [comment]
pyocclient doesn't operate on your locally mounted dav, it doesn't require it at all.

You need to use the path relative to your ownCloud. So instead of "~/oc/test/helloWorld.txt" try with the path "test/helloWorld.txt".

**Comment by avatar-lavventura** [comment]
Thank you sir. I have tried what you said, but gives the same error :(

```
  File "alper.py", line 16, in <module>
    oc.share_file_with_user( "test/helloWorld.txt"", "3d8e2dc2-b855-1036-807f-9dbd8c6b1579@b2drop.eudat.eu")
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1246, in share_file_with_user
    self._check_ocs_status(tree)
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1602, in _check_ocs_status
    raise OCSResponseError(r)
owncloud.owncloud.OCSResponseError: OCS error: 404
```

**Comment by PVince81** [comment]
then maybe the target user doesn't exist ? or needs to use a different user id format ?

without owncloud.log entries it will be difficult to know... You need access to "data/owncloud.log" on the ownCloud server. If you don't have access or aren't an admin you won't see it.

**Comment by avatar-lavventura** [comment]
Yes the user exists, Please see. I tried user's email address, federationCloudId@domain, both didn't helped.

<img width="544" alt="screen shot 2017-06-23 at 13 33 42" src="https://user-images.githubusercontent.com/18537398/27478520-a435b0da-5818-11e7-9c23-8bb1abf90a8f.png">

**Comment by PVince81** [comment]
It needs to be a local user. AFAIK this API cannot create shares to federated users.

**Comment by avatar-lavventura** [comment]
What do you mean by `local user`? The users created using this b2drop are default federated users all the time :( I was trying to share folder between 2 federated users. @PVince81 

I guess my only solution is to do it by hand.

**Comment by PVince81** [comment]
A function is missing to share with federated users, to be added later.

**Comment by avatar-lavventura** [comment]
Thank you sir! I appreciated your valuable help and time.

**Comment by remjg** [comment]
After looking at the source code, everything seems to be ready for sharing with federated users.
In order to do that, you have to use the keyword argument `remote_share=True`.

Example:

    oc.share_file_with_user('myfile', 'user@domain.fr/owncloud/', remote_user=True)

Be careful with the final `/`, it doesn't work without it ! Hope that helps !

Rémi.

**Comment by remjg** [comment]
Maybe a naïve way of improving the situation (I learned Python this week, I'm not a programmer):

    @@ -1234,6 +1234,8 @@
             :param perms (optional): permissions of the shared object
                 defaults to read only (1)
                 http://doc.owncloud.org/server/6.0/admin_manual/sharing_api/index.html
    +        :param remote_user (optional): True if it is a federated users
    +            defaults to False if it is a local user
             :returns: instance of :class:`ShareInfo` with the share info
                 or False if the operation failed
             :raises: HTTPResponseError in case an HTTP error status was returned
    @@ -1244,6 +1246,8 @@
                     or ((not isinstance(user, six.string_types)) or (user == ''))):
                 return False
     
    +        if (not user.endswith('/')) and remote_user:
    +            user = user + '/'
             path = self._normalize_path(path)
             post_data = {
                 'shareType': self.OCS_SHARE_TYPE_REMOTE if remote_user else

**Comment by PVince81** [comment]
@remjg sounds good, can you put that in PR form ?

**Comment by remjg** [comment]
Not sure how, but I think I have made my very first pull request!

https://github.com/owncloud/pyocclient/pull/201

**Comment by avatar-lavventura** [comment]
@remjg : Thank you very much!! It works when I added `remote_user=True `.

Example:
`oc.share_file_with_user( 'helloWorld', '3d8e2dc2-b855-1036-807f-9dbd8c6b1579@b2drop.eudat.eu', remote_user=True )`

**Comment by avatar-lavventura** [comment]
@PVince81 @remjg 

I am not sure what has been updated but this does not work anymore:

```
    oc.share_file_with_user('helloWorld', '3d8e2dc2-b855-1036-807f-9dbd8c6b1579@b2drop.eudat.eu', remote_user=True)
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1255, in share_file_with_user
    raise HTTPResponseError(res)
owncloud.owncloud.HTTPResponseError: HTTP error: 401
```
