### ISSUE TITLE
put_file does not work.

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#200]
Following link: https://b2drop.eudat.eu/s/DfQlm5J42nEGnH7 holds the files and folders (publicly accessible). Please not that no user name and password is required.

I can download the zip file via:

    wget https://b2drop.eudat.eu/s/DfQlm5J42nEGnH7/download

This will generate a download file. I can unzip it via: `unzip download`

On the website's GUI, when I click plus sign and than `upload` sign it opens a section where I can select which files I want to download. I would like to do all this operations via console.

[![enter image description here][1]][1]
[![enter image description here][2]][2]

I have did following code piece but it did not upload the file. Do you have any advice?

```
oc = owncloud.Client('https://b2drop.eudat.eu/')
oc.login('username@domain.edu', password ); 
oc.put_file( "https:/b2drop.eudat.eu/s/DfQlm5J42nEGnH7", "path/to/upload/run.sh")
oc.put_file( "/s/DfQlm5J42nEGnH7", "path/to/upload/run.sh")
oc.put_file( "/DfQlm5J42nEGnH7", "path/to/upload/run.sh")
```

  [1]: https://i.stack.imgur.com/Bt2D7.png
  [2]: https://i.stack.imgur.com/jvc4m.png

**Comment by PVince81** [comment]
With pyocclient you cannot access public links directly as they are not a subpath of "remote.php/webdav".

Closing in favor of https://github.com/owncloud/pyocclient/issues/12
