### ISSUE TITLE
R/O annonymous access, is it possible?

### ISSUE THREAD

**Issue by yarikoptic** [owncloud/pyocclient#205]
Looking for a way to get a list of files available on owncloud folder to which I am given a URL and could download files manually in the web ui.  ATM pyocclient requires "login" operation to go first.  I wondered if there could be a mode of operation for R/O operations (get list of files, get files, etc) which would not require authentication?

thanks in advance for the clarification

**Comment by PVince81** [comment]
Every user has their own list of files in ownCloud. What list of files would you expect to see if there was an anonymous user ? There is currently no such thing.

Or are you talking about public link shares ?

**Comment by yarikoptic** [comment]
yes.  I am provided a URL which points to a folder structure.  Full plan is to "crawl" it and create a git-annex repo pointing to those files so I could easily download only the ones I need etc.

**Comment by PVince81** [comment]
I assume you are talking about public link shares. In any case, pyocclient doesn't support anything alike. 

Closing in favor of https://github.com/owncloud/pyocclient/issues/12
