### ISSUE TITLE
error with share_file_with_link

### ISSUE THREAD

**Issue by sgiunchi** [owncloud/pyocclient#214]
I'm trying to use pyocclient, ubuntu 16.04 with python3.52.
Installed with easy_install3 pyocclient.

I copied the example, but trying to share a folder:

#!/usr/bin/env python3
import owncloud
oc = owncloud.Client('http://server/owncloud')

oc.login('user', 'pass')
try:
    oc.mkdir('testdir')
except:
    pass

link_info = oc.share_file_with_link('testdir')

Traceback (most recent call last):
  File "./test2.py", line 15, in <module>
    link_info = oc.share_file_with_link('paghe')
  File "/usr/local/lib/python3.5/dist-packages/pyocclient-0.4-py3.5.egg/owncloud/owncloud.py", line 833, in share_file_with_link
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/pyocclient/issues/218
