### ISSUE TITLE
oc.share_file_with_user: owncloud.owncloud.HTTPResponseError: HTTP error: 401

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#215]
On this issue: (https://github.com/owncloud/pyocclient/issues/199#issuecomment-309497823)

`pyocclient==0.4`

Following line was working:

`oc.share_file_with_user( 'helloWorld', '3d8e2dc2-b855-1036-807f-9dbd8c6b1579@b2drop.eudat.eu', remote_user=True )`

After the upgrade I guess I am having following error message:

```
    oc.share_file_with_user('helloWorld', '3d8e2dc2-b855-1036-807f-9dbd8c6b1579@b2drop.eudat.eu', remote_user=True)
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1255, in share_file_with_user
    raise HTTPResponseError(res)
owncloud.owncloud.HTTPResponseError: HTTP error: 401
```

**[Q]** How could I fix this?

**Comment by avatar-lavventura** [comment]
I was trying to share file with the already logged in user.  When I try with some other user-id it is fixed.

**Comment by PVince81** [comment]
> After the upgrade

what upgrade ? ownCloud core ? what ownCloud server are you using ?

**Comment by avatar-lavventura** [comment]
@PVince81 I am using latest version, everything works perfectly fine. Sorry I was not able to close the issue.

**Comment by PVince81** [comment]
No worries. Glad to hear it works!
