### ISSUE TITLE
error 500 using oc.put_file

### ISSUE THREAD

**Issue by MaxiReglisse** [owncloud/pyocclient#220]
I'm having trouble sending a file to a directory:

    >>> oc.put_file('testdir/remotefile.txt', 'localfile.txt')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/dist-packages/owncloud/owncloud.py", line 507, in put_file
    **kwargs
      File "/usr/local/lib/python3.6/dist-packages/owncloud/owncloud.py", line 616, in _put_file_chunked
    headers=headers
      File "/usr/local/lib/python3.6/dist-packages/owncloud/owncloud.py", line 1679, in _make_dav_request
    raise HTTPResponseError(res)
    owncloud.owncloud.HTTPResponseError: HTTP error: 500

NB: put_file() fails with error 500, but the localfile.txt is actually sent to the destination folder!

On the other hand, it works without problems with the command curl:

    curl -H 'Authorization: Basic Y...2' -T localfile.txt http://nextcloud-mshe.univ-fcomte.fr/remote.php/dav/files/admin/testdir/remotefile.txt

i tried with python2 and python3.
owncloud  server : 9.1.8
pyocclient : 0.4

In the owncloud server log, we can read the following lines:
    {"reqId":"Si0R01H5S7hbMjn6I9\/0","remoteAddr":"172.20.74.124","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_filecache\\\" SET \\\"mtime\\\" = GREATEST(\\\"mtime\\\", ?), \\\"etag\\\" = ? WHERE (\\\"storage\\\" = ?) AND (\\\"path_hash\\\" IN ('d41d8cd98f00b204e9800998ecf8427e', '45b963397aa40d4a0063e0d85e4fe7a1', 'a02c96afea6d850f30883ffeb9d76563'))' with params [\\\"1537967228.3743448\\\", \\\"5bb1d53254ead\\\", 1]:\\n\\nSQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entr\\u00e9e invalide pour l'entier : \\u00ab 1537967228.3743448 \\u00bb\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE \\\"oc_file...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(209): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE \\\"oc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php(87): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/HomePropagator.php(48): OC\\\\Files\\\\Cache\\\\Propagator->propagateChange('files\\\/testdir\\\/r...', '1537967228.3743...', 0)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Updater.php(137): OC\\\\Files\\\\Cache\\\\HomePropagator->propagateChange('files\\\/testdir\\\/r...', '1537967228.3743...', 0)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(314): OC\\\\Files\\\\Cache\\\\Updater->update('files\\\/testdir\\\/r...', '1537967228.3743...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1141): OC\\\\Files\\\\View->writeUpdate(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/testdir\\\/r...', '1537967228.3743...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(551): OC\\\\Files\\\\View->basicOperation('touch', '\\\/testdir\\\/remote...', Array, '1537967228.3743...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(208): OC\\\\Files\\\\View->touch('\\\/testdir\\\/remote...', '1537967228.3743...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(136): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #61)\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('remotefile.txt', Resource id #61)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('testdir\\\/remotef...', Resource id #61, NULL)\\n#15 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91,\"User\":\"admin\"}","level":4,"time":"2018-10-01T08:05:06+00:00","method":"PUT","url":"\/remote.php\/webdav\/testdir\/remotefile.txt","user":"admin"}

Thanks in advance for your help.

**Comment by PVince81** [comment]
seems to be related to mtimes that are float instead of integer.

you might need this fix in your server https://github.com/owncloud/core/pull/28066 or upgrade to OC 10
