### ISSUE TITLE
Provide functions to manage users

### ISSUE THREAD

**Issue by PVince81** [owncloud/pyocclient#64]
OC 8 now has a provisioning API (OCS)

Question here is whether it's a good time to split pyocclient into modules or just add extra functions in the main class.

Note: this will also need a version/capabilities check based on https://github.com/PVince81/pyocclient/issues/39
If we go the modules route, modules should be able to provide required dependencies (minimum OC version / capability)

@Gomez

**Comment by Gomez** [comment]
I am still thinking about the integration of a wrapper for ./occ. That would be a good place for a module too. 
Modules as own py files with an extra import?

**Comment by PVince81** [comment]
An extra import sounds good.
One concern is whether the API consumer needs to instantiate a Client for every module or whether we can make the main module return submodules ?
For example:
```python
client = owncloud.Client(...)
client.put_file_contents(...) # for file operations
client.get_users_module().create_user(...) # for user operations
```
or should it be:
```python
client = owncloud.Client(...)
client.put_file_contents(...) # for file operations

# instantiate a client for the users module
users = owncloud.users.Client(...)
users.create_user(...)
```

What do you think ?

I find the first approach better because we can reuse the auth/requests object.

**Comment by PVince81** [comment]
I raised another ticket to discuss modules: https://github.com/PVince81/pyocclient/issues/67

Let's keep this one here for the "users API" implementation.

**Comment by jnfrmarks** [comment]
I like the first approach.  

In the case of approach 2, If we have to create users and groups, then we would need create two client instances: one to create the users and one to create the groups (assuming I'm understanding what you said ... ;) )

**Comment by PVince81** [comment]
@jnfrmarks as discussed, can you send a PR that adds the functions to manage users ? (with unit tests, if possible :smile:)

**Comment by PVince81** [comment]
Functions were added through https://github.com/owncloud/pyocclient/pull/76
