### ISSUE TITLE
owncloud.py is not installed when installing via pip

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/pyocclient#75]
1. run: pip install pyocclient
2. See what's installed
3. owncloud.py is missing

```
jennifer@ubuntu-14-client:~/pyocclient$ ls /usr/local/lib/python2.7/dist-packages/
owncloud                 robotframework-2.8.6.egg-info
pyocclient-0.1.egg-info  unittest_data_provider
robot                    unittest_data_provider-1.0.1.egg-info
jennifer@ubuntu-14-client:~/pyocclient$ ls /usr/local/lib/python2.7/dist-packages/owncloud/
__init__.py  __init__.pyc  test

```

**Comment by PVince81** [comment]
It used to be called "__init__.py" in the past for version 0.1.
Please don't use that outdated version but only use the git version for now.

You might be able to install it using a requirements.txt file like this:
```
-e git+git@github.com:owncloud/pyocclient.git@master#egg=pyocclient
```
Then `pip install -r requirements.txt`

Note: at some point I hope to release 0.2, but there is still work to be completed for that.
